name: Deploy PR Preview

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, closed]

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Deploy Preview
    
    # Skip if PR is from a fork (no secrets access)
    if: github.event.pull_request.head.repo.full_name == github.repository
    
    environment: preview
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        if: github.event.action != 'closed'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        if: github.event.action != 'closed'
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        if: github.event.action != 'closed'
        run: npm ci

      - name: Run type check
        if: github.event.action != 'closed'
        run: npm run type-check

      - name: Run linting
        if: github.event.action != 'closed'
        run: npm run lint

      - name: Build application
        if: github.event.action != 'closed'
        run: npm run build

      - name: Deploy Preview to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: portfolio-website
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'